import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import ProductCard from '../components/ProductCard/ProductCard'

const Home: NextPage = () => {
	const [products, setProducts] = React.useState(null);
	
	React.useEffect(() => {
		fetch('/products.json')
		.then(res => res.json())
		.then(res => ({ res }))
		.then(res => setProducts(res.res))
		.catch(err=>console.log(err))
	}, [])
	
	return (
		<React.Fragment>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container pt-4">
				<div className="row">
					{products && products.map((item: object, i: number)=> 
						<div className="col-3 mb-4" key={i}>
							<ProductCard data={item}/>
						</div>
					)}
				</div>
			</div>
		</React.Fragment>
	)
}

export default Home
